apiVersion: v1
kind: Service
metadata:
  name: springbootdemo02
  namespace: spring-test
spec:
  type: NodePort
  selector:
    app: springbootdemo02
  ports:
  - protocol: TCP
    port: 8010
    targetPort: 8010
    nodePort: 30003